# use_frameworks!

platform :ios, '9.0'

target 'SJAudioPlayer_Example' do
  pod 'SJAudioPlayer', :path => '../'
  pod 'SJMediaCacheServer'

  target 'SJAudioPlayer_Tests' do
    inherit! :search_paths

    
  end
end
